name:                FortH
version:             0.1.0.0
github:              "annika/FortH"
license:             BSD3
author:              "annika"
maintainer:          "annika.rings@freenet.de"
copyright:           "GPL"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/annika/FortH#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- text
- containers
- parsec
- QuickCheck
- hspec
- generic-random
- generic-arbitrary
- parsec-numbers
- split
- vector
- transformers
- lens
- aeson
- lens-aeson

library:
  source-dirs: src

executables:
  FortH-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FortH

tests:
  FortH-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - FortH
